name: advanced-datamining
channels:
  - conda-forge
dependencies:
  - matplotlib=3.8
  - notebook=7.2
  - pandas=2.2
  - pip=24
  - python=3.12
  - scikit-learn=1.5
  - tensorflow=2.16
  - pip:
    - nbconvert[webpdf]
    - poetry
